💄[Design] 헤더 네비게이션 바 디자인 색상 변경
codeit-team3/FE pull request #90
Opened 2024-12-07 10:51 UTC by haegu97

## #️⃣연관된 이슈

> #9 

## 📝작업 내용

> - 헤더 네비게이션 바 색상을 피그마 기준으로 변경
- 네비게이션 버튼 클릭시 텍스트 색상 변경

### 미리보기, 사용방법 및 결과물

![스크린샷 2024-12-07 오후 7 50 25](https://github.com/user-attachments/assets/9178e247-f803-4c7d-8a90-5a7deaa3667c)

### 기타 참고사항

2024-12-08 12:44 UTC, cloud0406 requested changes
수고하셨습니다~.~
바뀐 디자인 명명은 제가 Pr만들어서 적용 후 말씀드리겠습니다~

2024-12-08 12:44 UTC, cloud0406 commented on src/components/header/HeaderBar.tsx
> +    <nav className="fixed top-0 w-full bg-green-normal px-4 text-white md:px-7">
p3: 이 부분은 피그마에서 color system 명명이 바뀜에 따라 다시 수정되어야할 것 같습니다~ 추후에 제가 바뀐 명명대로 새로 Pr올리고 전달드리면 수정하시면 될 것 같아요!

2024-12-09 01:29 UTC, haegu97 commented on src/components/header/HeaderBar.tsx
> +    <nav className="fixed top-0 w-full bg-green-normal px-4 text-white md:px-7">
넵!

2024-12-09 01:38 UTC, sunnwave approved these changes

2024-12-09 01:38 UTC, sunnwave commented
수고하셨습니다~

2024-12-09 03:58 UTC, cloud0406 approved these changes

2024-12-09 04:33 UTC, cloud0406 approved these changes

2024-12-09 05:08 UTC, merged