♻️[Refactor] common DropDown UI 리팩토링 #51 #84
codeit-team3/FE pull request #93
Opened 2024-12-08 08:49 UTC by sunnwave

## #️⃣연관된 이슈
#51 #84
> ex) #이슈번호, #이슈번호

## 📝작업 내용
DropDown 컴포넌트 리팩토링
> 이번 PR에서 작업한 내용을 간략히 설명해주세요

### 미리보기, 사용방법 및 결과물
<img width="178" alt="스크린샷 2024-12-08 오후 5 35 57" src="https://github.com/user-attachments/assets/563a1503-51e1-4fe5-8447-d9224da7745d">
<img width="178" alt="스크린샷 2024-12-08 오후 5 36 18" src="https://github.com/user-attachments/assets/b8382cfe-61dd-452b-814c-8cda55cc636e">
<img width="183" alt="스크린샷 2024-12-08 오후 5 36 31" src="https://github.com/user-attachments/assets/0635854e-f654-4074-94d8-dbf31fa87700">

### 기타 참고사항
- 기존 props variant(navbar, filtering, sorting)에서 sorting을 별도의 컴포넌트로 분리했습니다.

2024-12-08 12:38 UTC, yunsung-hodoopapa approved these changes

2024-12-08 12:38 UTC, yunsung-hodoopapa commented on src/components/drop-down/DropDown.tsx
> +  const getButton = (
renderButton으로 함수명을 보다 정확하게 바꾸어도 좋을 것 같습니다 :-)
variant를 예시로 들기는 했지만, type을 사용해도 좋을 것 같아요!

2024-12-08 12:38 UTC, yunsung-hodoopapa commented on src/components/drop-down/DropDown.tsx
> +          <button
뭔가 공통 컴포넌트인 버튼 컴포넌트의 props를 추가해서 아이콘을 포함할 수 있도록 개선해봐도 좋을 것 같습니다. @wynter24

2024-12-08 12:50 UTC, cloud0406 requested changes
수고하셨습니다~.~
색상관련해서 새로 바뀐 명명대로 새로 Pr을 올려두겠습니다! 바뀐 내용대로 수정하시고 다시 올려주시면 감사하겠습니다~

2024-12-08 12:50 UTC, cloud0406 commented on public/icons/IcDropDown.tsx
> +      className={`${isActive ? color : 'stroke-gray-dark-hover'}`}
p3: 이 부분은 피그마에서 color system 명명이 바뀜에 따라 다시 수정되어야할 것 같습니다~ 추후에 제가 바뀐 명명대로 새로 Pr올리고 전달드리면 수정하시면 될 것 같아요!

2024-12-09 02:46 UTC, cloud0406 approved these changes

2024-12-09 05:09 UTC, merged